services:
  # processor:
  #   build: 
  #     context: "."
  #     args:
  #       - R_RENV_CACHE_HOST=./server/renv/cache
  #     dockerfile: "docker/backend.dockerfile"
  #   entrypoint: "Rscript processor.R"
  #   volumes:
  #     - "./server/temp:/server/temp"
  #     - "./server/logs:/server/logs"
  #   env_file:
  #     - server/.env      
  backend:
    build: 
      context: "."
      args:
        - R_RENV_CACHE_HOST=./server/renv/cache
      dockerfile: "docker/backend.dockerfile"
    expose:
      - "8000"
    ports: 
      - "8000:8000"
    volumes:
      - "./server/temp:/server/temp"
      - "./server/logs:/server/logs"
    env_file:
      - server/.env
  frontend:
    build:
      context: "."
      dockerfile: "docker/frontend.dockerfile"
      args:
        - GIT_TAG=${GIT_TAG:-unknown}
        - GIT_BRANCH=${GIT_BRANCH:-unknown}
        - LAST_COMMIT_DATE=${LAST_COMMIT_DATE:-unknown}
    ports: 
      - "8080:80"
    environment: 
      API_HOST: "http://backend:8000"
      SERVER_NAME: localhost


