services:
  processor:
    build: 
      context: "."
      dockerfile: "docker/backend.dockerfile"
    entrypoint: "Rscript processor.R"
    volumes:
      - "./server/temp:/server/temp"
      - "./server/logs:/server/logs"
    env_file:
      - server/.env      
  backend:
    build: 
      context: "."
      dockerfile: "docker/backend.dockerfile"
      args:
        COMETS_R_PACKAGE_REF: "v3.0-dev"
        GITHUB_PAT: $GITHUB_PAT
    expose:
      - "8000"
    ports: 
      - "8000:8000"
    volumes:
      - "./server/temp:/server/temp"
      - "./server/logs:/server/logs"
    env_file:
      - server/.env
  frontend:
    build:
      context: "."
      dockerfile: "docker/frontend.dockerfile"
    ports: 
      - "8080:80"
    environment: 
      API_HOST: "http://backend:8000"
      SERVER_NAME: localhost


